### ISSUE TITLE
It seems like after disconnect from Karura, it doesn't connect again

### ISSUE THREAD

**Issue by yingjingyang** [Manta-Network/manta-front-end#1003]
the page doesn't change until I refresh the page

![截屏2023-05-06 上午11.45.47.png](https://images.zenhubusercontent.com/63e10f6258011a5593f8116e/c6c3eefa-afc1-4d52-9aa8-c51e7b2db0e9)

**Comment by Kevingislason** [comment]
I'm able to reconnect

**Comment by Kevingislason** [comment]
Closing for now, will reopen if we encounter later
