### ISSUE TITLE
Sometimes when I click "To Private", there is no response

### ISSUE THREAD

**Issue by yingjingyang** [Manta-Network/manta-front-end#1005]
Steps ( but can't reproduce )
1) bride KAR from Karura to Calamari
2) switch to MantaPay page
3) Choose "Kar" as "Public",  and do the transact "Public" to "Private"
4) click the button "To private", but there is no response

![image.png](https://images.zenhubusercontent.com/63e10f6258011a5593f8116e/994cffaf-43b6-4354-a650-bb22d0f3ea48)

**Comment by Kevingislason** [comment]
I can't reproduce this either, but I can add logging at least so we can catch it later.
