### ISSUE TITLE
After transact of "Private" to "Public" success, the zk balance not updated

### ISSUE THREAD

**Issue by yingjingyang** [Manta-Network/manta-front-end#1006]
steps:
1) do transact of "Private" to "Public"
2) get transaction success notification, and the wallet balance updated correct, but the balance showed on page not updated

![image.png](https://images.zenhubusercontent.com/63e10f6258011a5593f8116e/939f7341-93f5-4aca-8713-21b36c91382b)

**Comment by Kevingislason** [comment]
I wasn't able to reproduce this. If I recall right, this might have been a Manta Wallet issue. Would you mind testing this again with the latest version of Manta Wallet?

**Comment by Kevingislason** [comment]
On the latest extension there is a new interface to subscribe to balances

**Comment by Kevingislason** [comment]
Require users to update to v2 extension (version with subscription)
We will release stablecoin PR after that is ready
