### ISSUE TITLE
Sometimes, it takes long time to get the Dai balance from Karura

### ISSUE THREAD

**Issue by yingjingyang** [Manta-Network/manta-front-end#1008]
[Video link](https://drive.google.com/file/d/1658ARJoDhKfb048Km0RRdUpZhIH0nVZE/view?usp=sharing)

**Comment by Kevingislason** [comment]
I've seen this sometimes. It seems to be some kind of issue with Karura's web socket, since it is not very consistent. I'm not sure there is much we can do.
