### ISSUE TITLE
while the balance is loading, the button is clickable

### ISSUE THREAD

**Issue by yingjingyang** [Manta-Network/manta-front-end#1009]
reproduct step:
1) Choose "Karura" as "From", "Calamari" as "To"
2) choose token "KAR", and input the amount
3) choose the other token, such as "Dai", "USDC"

![截屏2023-05-08 上午11.45.34.png](https://images.zenhubusercontent.com/63e10f6258011a5593f8116e/5c5a8a14-39af-4784-9abc-a98b094fa496)

**Comment by Kevingislason** [comment]
Unless you can initialize a transaction by clicking, I don't think this is necessarily a bug. We could grey out the button, but I don't know if that would be helpful. It's possible that having the button flickering when you change coins could be annoying. We can discuss with Chloe.
