### ISSUE TITLE
notification of minimum amount for zk transaction is incorrect

### ISSUE THREAD

**Issue by yingjingyang** [Manta-Network/manta-front-end#1011]
![截屏2023-05-08 下午1.43.44.png](https://images.zenhubusercontent.com/63e10f6258011a5593f8116e/7e29caaf-5c5c-4629-b6bb-f8ce9d6b745d)

**Comment by Kevingislason** [comment]
This looks correct to me. The min transaction is 0.1, and the amount entered in the form is 0.01

**Comment by Kevingislason** [comment]
need to add "zk" prefix
