### ISSUE TITLE
Improve UI Appearance of Signer Installation Modal

### ISSUE THREAD

**Issue by bhgomes** [Manta-Network/manta-front-end#104]
Right now it looks like this:

<img width="1680" alt="Screen Shot 2022-05-20 at 11 30 53" src="https://user-images.githubusercontent.com/9126085/169561956-093d46ba-2f06-4acc-a976-f3e915ff546d.png">

Some issues I think should be resolved:
1. Text should fit on one line and possibly with a larger font
2. The UI elements should be centered vertically on the page
3. Instead of saying "missing required software" we should use more inviting language and the UI should still work if the signer is not installed, just the private features won't work
4. Add a cookie to check if they have seen the popup before and only show it once, just like the cookie we have for the light/dark mode
5. Make the modal not cover the entire screen, but some smaller central region
6. Embed the installation mechanism right in the frontend instead of needing to jump to a landing page (but give them the option to go there)
7. Add an installation link/button on the frontend somewhere else (probably where it says signer on the top right) so that they can still get the signer even if they have dismissed the modal
8. Add an explicit `x` button on the modal so they can be certain they are closing it

**Comment by Kevingislason** [comment]
May also want to consider splitting modal into two modals--1 for signer, 1 for wallet

**Comment by Kevingislason** [comment]
Removed in #318
