### ISSUE TITLE
USDT balance is showed 0 in MantaPay page even it is not 0 in Bridge page

### ISSUE THREAD

**Issue by yingjingyang** [Manta-Network/manta-front-end#1173]
MantaPay page:

![截屏2023-07-17 上午11.41.57.png](https://images.zenhubusercontent.com/63e10f6258011a5593f8116e/a3c87662-ccc5-416f-ba5c-080562ddecc5)

Bridge page:
![截屏2023-07-17 上午11.41.05.png](https://images.zenhubusercontent.com/63e10f6258011a5593f8116e/493c066a-e79f-47db-ab33-07ec9c088dc2)

**Comment by jasonintju** [comment]
close for now, only MANTA ACA DOT GLMR are online
