### ISSUE TITLE
popup token balance not updated in time when exchange "From" & "To"

### ISSUE THREAD

**Issue by yingjingyang** [Manta-Network/manta-front-end#1174]
reproduce step:
1) "From": Acala ,  "To": Manta
2) Check token balance in popup & page
3) exchange "From" & "To"
4) check token balance in popup & page

Expect: token balance updated in no time
Actual: token balance is not updated

token balance in page after exchange:
![截屏2023-07-17 上午11.56.16.png](https://images.zenhubusercontent.com/63e10f6258011a5593f8116e/2fab422f-0e97-476e-9388-38e1f44b0620)

token balance in popup after exchange:
![截屏2023-07-17 上午11.56.24.png](https://images.zenhubusercontent.com/63e10f6258011a5593f8116e/16b53532-b6d5-42a6-8e32-cd8e77f13198)

**Comment by jasonintju** [comment]
close for now, only MANTA ACA DOT GLMR are online
