### ISSUE TITLE
“Estimate Receive” is NAN when click "Max"

### ISSUE THREAD

**Issue by yingjingyang** [Manta-Network/manta-front-end#1221]
![截屏2023-08-08 下午3.18.11.png](https://images.zenhubusercontent.com/63e10f6258011a5593f8116e/aadb7e06-8fe1-4643-a353-cfb63596040b)

**Comment by yingjingyang** [comment]
![截屏2023-08-10 下午3.55.14.png](https://images.zenhubusercontent.com/63e10f6258011a5593f8116e/0832f50a-7bd3-4710-baa3-bb1a7a595683)

**Comment by wuyahuang** [comment]
[Uploading... 14531691665302_.pic.jpg]

**Comment by wuyahuang** [comment]
![14531691665302_.pic.jpg](https://images.zenhubusercontent.com/63dbc9bba94d54df3d2f8990/93a243f8-da72-4f91-9759-7d508c567e0f)
