### ISSUE TITLE
amount is incorrect when click "Select max"

### ISSUE THREAD

**Issue by yingjingyang** [Manta-Network/manta-front-end#1222]
reproduce steps:
1) Choose bridge from "Manta" to "Ethereum"
2) click "Select Max"
3) then click ⇄ 
4) click "Select Max"

Expect Result:
amount is correct when click "Select Max"

Actual Result:
amount is incorrect

[Video Link](https://drive.google.com/file/d/1sqzu0Mc4bxdE8ll0unRwSeMnj4MQDpSx/view?usp=sharing)

**Comment by yingjingyang** [comment]
when click "select max", nothing changed

**Comment by jasonintju** [comment]
close
