### ISSUE TITLE
need to handle interface error

### ISSUE THREAD

**Issue by yingjingyang** [Manta-Network/manta-front-end#1230]
![image.png](https://images.zenhubusercontent.com/63e10f6258011a5593f8116e/d4df1474-63b9-4a9c-8841-17f70f60a162)

![image.png](https://images.zenhubusercontent.com/63e10f6258011a5593f8116e/e9ee07b9-6d67-4e86-a34f-0ea9b9f80ea4)

**Comment by jasonintju** [comment]
also need to confirm where to show the error msg with @Choely

**Comment by wuyahuang** [comment]
It will keep retrying if the network fails.
