### ISSUE TITLE
button text should be “Sending" when receiving free GLMR

### ISSUE THREAD

**Issue by yingjingyang** [Manta-Network/manta-front-end#1231]
current:

![image.png](https://images.zenhubusercontent.com/63e10f6258011a5593f8116e/4c532cbd-8d90-4b39-abf7-d5916b269661)

expect:

![image.png](https://images.zenhubusercontent.com/63e10f6258011a5593f8116e/3bb4be9f-5ef1-4624-a543-319606dd60f8)

**Comment by jasonintju** [comment]
change to 'Processing'
