### ISSUE TITLE
button text should be "Approving" when waiting for approval for cela

### ISSUE THREAD

**Issue by yingjingyang** [Manta-Network/manta-front-end#1232]
reproduce steps:
1) click button to approve transfer token from Moonbeam to Ethereum

Expect Result:
button text should be “Approving" 

Actual Result:
button text is "Transfer"

![image.png](https://images.zenhubusercontent.com/63e10f6258011a5593f8116e/96fa2b4f-841e-49b0-95df-f38498b7a18e)

**Comment by jasonintju** [comment]
also 'Processing'
