### ISSUE TITLE
doesn't show any error message when refuse to approval for cela

### ISSUE THREAD

**Issue by yingjingyang** [Manta-Network/manta-front-end#1233]
可以改成：错误提示：Approval failed. Please try again.
按钮文案：Approve again，然后点击再次发起approve

![image.png](https://images.zenhubusercontent.com/63e10f6258011a5593f8116e/28993d03-8bac-4290-9686-eae69f7d3ba6)

**Comment by jasonintju** [comment]
will show whatever err msg metamask give us

**Comment by jasonintju** [comment]
Keep 'Approve' text unchanged
