### ISSUE TITLE
Manta balance is still 0 after finish bridging from Ethereum to Manta, it'll be updated after refresh the page

### ISSUE THREAD

**Issue by yingjingyang** [Manta-Network/manta-front-end#1260]
transaction hash:

https://moonbase.moonscan.io/tx/0xf58ff8da110c4ae63e31ada26a95036cf2a7e5b56b65aab0121ec18d47c86aa7

![image.png](https://images.zenhubusercontent.com/63e10f6258011a5593f8116e/6a61120d-d24a-447d-8299-c64a18a09af7)

**Comment by jasonintju** [comment]
didn't reproduce it. make sure it's the same polkadot address
