### ISSUE TITLE
the "Bridge Fees" & "Estimate Receive" are not accurate

### ISSUE THREAD

**Issue by yingjingyang** [Manta-Network/manta-front-end#1272]
I have tried to bridge 10 Manta from Ethereum to Manta, and finally I have received 9.9 Manta on Manta side

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBa2tDIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--0a6afb7d775df84c33ef263ddfac161b2ebc4e59/image.png)

**Comment by jasonintju** [comment]
xcm  setting fee is not accurate on testnet, we will update the accurate fee on mainnet

**Comment by jasonintju** [comment]
hold for now
