### ISSUE TITLE
can't get "Bridge Fees" & "Estimate Receive" when input amount is too large

### ISSUE THREAD

**Issue by yingjingyang** [Manta-Network/manta-front-end#1275]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbk1DIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--d400f2fa2797099e88ce8bb7698bc6adbc560fb1/%E6%88%AA%E5%B1%8F2023-08-14%20%E4%B8%8B%E5%8D%884.04.43.png)

**Comment by jasonintju** [comment]
See the button text
