### ISSUE TITLE
"Destination fee" should be transfer token

### ISSUE THREAD

**Issue by yingjingyang** [Manta-Network/manta-front-end#1313]
Manta network:

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbUJYIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--63ba3883432ed407ebf2df6898367643e310262d/%E6%88%AA%E5%B1%8F2023-08-31%20%E4%B8%8B%E5%8D%884.06.39.png)

Calamari network:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbU5YIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--25f85de94451618d57feb99602057a98ba6aa86b/%E6%88%AA%E5%B1%8F2023-08-31%20%E4%B8%8B%E5%8D%884.08.36.png)

**Comment by jasonintju** [comment]
DAI USDC WBNB WETH tBTC these five assets, dest fee is 'GLMR'
