### ISSUE TITLE
tTBC name should be "tBTC v2"

### ISSUE THREAD

**Issue by yingjingyang** [Manta-Network/manta-front-end#1314]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbTlYIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--b815b77f7e30a353decd498748ba3f818d354471/%E6%88%AA%E5%B1%8F2023-08-31%20%E4%B8%8B%E5%8D%884.20.16.png)

**Comment by jasonintju** [comment]
keep tBTC as PD said
