### ISSUE TITLE
most of the time, page is keep loading when switch from MantaPay to Bridge

### ISSUE THREAD

**Issue by yingjingyang** [Manta-Network/manta-front-end#1317]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbFZkIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--a1175bc14e384f13e10ddac900054091fdcca7df/image.png)

**Comment by jasonintju** [comment]
maybe network issues, I can't reproduce it.
