### ISSUE TITLE
dApp misbehave when Talisman is locked

### ISSUE THREAD

**Issue by stechu** [Manta-Network/manta-front-end#161]
How to reproduce:
1. in a brave browser, create a profile without having polkadot.js installed.
2. install talisman
3. open app.dolphin.manta.network while talisman is locked.
 
<img width="1124" alt="Screen Shot 2022-06-13 at 9 28 08 PM" src="https://user-images.githubusercontent.com/720571/173474141-c4d19558-3a09-4ae2-860b-bb13f6290e37.png">

**Comment by Kevingislason** [comment]
fixed in #269
