### ISSUE TITLE
Send amount input discolored in some circumstances

### ISSUE THREAD

**Issue by Kevingislason** [Manta-Network/manta-front-end#174]
Need to figure out how to consistently reproduce
<img width="682" alt="Screen Shot 2022-06-16 at 5 26 18 PM" src="https://user-images.githubusercontent.com/33131270/174188799-315d9ab1-d4f5-4f38-bee6-6ce8df775b17.png">

**Comment by dansofter** [comment]
This happens when you click one of the input history instead of typing in.
