### ISSUE TITLE
After clicking away the Signer Install modal I won't be able to find the signer

### ISSUE THREAD

**Issue by bhgomes** [Manta-Network/manta-front-end#261]
I think the top right signer section (or wherever the signer status is displayed) should be clickable to download the signer:

<img width="1912" alt="Screen Shot 2022-09-26 at 11 09 40" src="https://user-images.githubusercontent.com/9126085/192313668-cfd27326-17ab-47b0-b23c-7240064cb997.png">

**Comment by Kevingislason** [comment]
closed in #318
