### ISSUE TITLE
Measure Page Quality

### ISSUE THREAD

**Issue by bhgomes** [Manta-Network/manta-front-end#266]
Add measurements using a tool like https://web.dev/measure to the release pipeline

**Comment by ECJ222** [comment]
This looks like an interesting feature, please can I get a reference to the release pipeline. and is this issue open for anyone to work on?

**Comment by Kevingislason** [comment]
@ECJ222 I believe only Brandon has permissions to alter the release pipeline. 

But we definitely appreciate your interest! Basically all other open issues without pending PRs are available. Feel free to message me on discord (KG#2190) if you'd like to talk.

**Comment by ECJ222** [comment]
Okay @Kevingislason, I will reach out.
