### ISSUE TITLE
Setup Branch Protection and Merging Rule

### ISSUE THREAD

**Issue by stechu** [Manta-Network/manta-front-end#30]
Branch protection and merging rule is needed after production.

**Comment by stechu** [comment]
@dansofter @Kevingislason  any proposal for the branch protection rule of this repo?

**Comment by Kevingislason** [comment]
perhaps obviously, but:
-enforce approving reviews 
-check CI pipelines pass (when these exist)
-enforce signed commits

Not sure what else people do tbh

**Comment by dansofter** [comment]
most organizations do this
- code reviewer only reviews the code and approved PR
- the owner of the PR should merge after approval and ensure no merge conflicts before merge

**Comment by stechu** [comment]
As a crypto project, there are risk of supply chain attack (for example, https://arstechnica.com/information-technology/2021/09/cryptocurrency-launchpad-hit-by-3-million-supply-chain-attack/ ), so probably a good idea to limit the number of people who can commit too.

**Comment by Kevingislason** [comment]
Btw, if anyone does this it needs to be you @stechu, I can't access repo settings
