### ISSUE TITLE
Brave blocks connection to manta signer by default

### ISSUE THREAD

**Issue by Kevingislason** [Manta-Network/manta-front-end#38]
If the user is using Brave browser, they need to "lower" their "shields" to connect to manta-signer (on localhost). I guess it thinks we are an ad tracker or something, maybe because the request is cross-origin. We should try to detect if the user is using Brave (is this possible?) and give them some kind of info notification. Or, we should get Brave to fix this, since you likely aren't going to have anything malicious running on your localhost.

see also https://github.com/Manta-Network/manta-signer/issues/26

**Comment by stechu** [comment]
Do you know why Polkadot.js app on Brave is able to connect to a localhost? (despite it is a web-socket connection)

**Comment by bhgomes** [comment]
We can move to https://github.com/snapview/tungstenite-rs in the future to replace the HTTP server.
