### ISSUE TITLE
show no message after install Talisman success but with no account

### ISSUE THREAD

**Issue by bhgomes** [Manta-Network/manta-front-end#397]
2023.1.13: It will be better to give me a specific release version & deadline (Joly)
2023.1.12: Will fix

May require input from product team.

**Comment by chloewang-p0x** [comment]
You have no account in Talisam. Please create one first.
https://www.figma.com/file/9nAYHsYlfHmyT8RL5P8ISZ/Manta-Pay?node-id=3365%3A658&t=CKZCDqTd0d8qIV8w-1
