### ISSUE TITLE
path in the sign message is different from browser path

### ISSUE THREAD

**Issue by bhgomes** [Manta-Network/manta-front-end#403]
2023.1.6: needs investigation, give a basic conclusion before next Thursday

**Comment by Kevingislason** [comment]
Assigned to Jason

**Comment by jasonintju** [comment]
I conducted an investigation about this issue. It seems that it might be a bug of polkadot-js extension.

I made a demo and also tested some polkadot official website, such as https://polkadot.js.org/apps/#/accounts and https://kusama.polkassembly.io/. They both have the same problem.

I have submitted an issue https://github.com/polkadot-js/extension/issues/1211 for polkadot-js extension, which described the details. Waiting for their response.

**Comment by jasonintju** [comment]
"The extension only keeps track of the initial URL where the script was injected." 
https://github.com/polkadot-js/extension/issues/1211#issuecomment-1431267546
And they add the 'support' label, maybe it will be supported soon.
