### ISSUE TITLE
Add user agreement and IP blocking for restricted countries

### ISSUE THREAD

**Issue by Kevingislason** [Manta-Network/manta-front-end#406]

**Comment by chloewang-p0x** [comment]
https://www.figma.com/file/9nAYHsYlfHmyT8RL5P8ISZ/Manta-Pay?node-id=3365%3A658&t=R47xmUEzPt0PM1X9-1

**Comment by jasonintju** [comment]
No user agreement yet. Only finish the IP blocking.
