### ISSUE TITLE
Slider color is too dark

### ISSUE THREAD

**Issue by yingjingyang** [Manta-Network/manta-front-end#458]
![Slider color is too dark.png](https://images.zenhubusercontent.com/63e10f6258011a5593f8116e/3346c78c-319b-46e9-805c-627716b5d0fb)

**Comment by yingjingyang** [comment]
[picture](https://drive.google.com/file/d/18U8fhhx6hwJwyS6hES9-bl662XdwoMFm/view?usp=sharing)

**Comment by yingjingyang** [comment]
[picture](https://drive.google.com/file/d/18U8fhhx6hwJwyS6hES9-bl662XdwoMFm/view?usp=sharing)

**Comment by zhangjing28** [comment]
@yeyeyeyehan Pls take a look at this slide bar, and give a better background color of this slide bar
