### ISSUE TITLE
Using "Shielded Address" 

### ISSUE THREAD

**Issue by stechu** [Manta-Network/manta-front-end#49]
We should give an user a clear distinction in UI between `shielded address` and `dolphin address`, my two cents:

<img width="449" alt="Screen Shot 2021-12-07 at 12 39 35 PM" src="https://user-images.githubusercontent.com/720571/145103388-21a94e68-6ead-4644-a02e-bbdbb1b56447.png">
<img width="420" alt="Screen Shot 2021-12-07 at 12 39 11 PM" src="https://user-images.githubusercontent.com/720571/145103476-b213ccbf-9670-44de-ae7c-8aa99fb385e9.png">

**Comment by bhgomes** [comment]
Closed as outdated.
