### ISSUE TITLE
Analyzing page display incorrect when jump from hom page

### ISSUE THREAD

**Issue by yingjingyang** [Manta-Network/manta-front-end#499]
1. User generating AI pictures, and was staying Analyzing page for 10 mins
2. User use the same account to login the SBT home page
3. Jump to the Analyzing page from SBT home page
4. The remaining time shows there is not correct; and don't show the pictures that user has uploaded

[video of Analyzing page](https://drive.google.com/file/d/1Ou2arHA4SGNOQFEErlZCAiU0eenZBIko/view?usp=sharing)

**Comment by zhangjing28** [comment]
Need help with this bug.
