### ISSUE TITLE
Progress bar in Analyzing page displayed incorrect

### ISSUE THREAD

**Issue by yingjingyang** [Manta-Network/manta-front-end#501]
design draft
![截屏2023-02-17 下午9.39.20.png](https://images.zenhubusercontent.com/63e10f6258011a5593f8116e/6e0e2014-baed-44d6-ac55-500c46f2f18b)

current website

![截屏2023-02-17 下午9.39.04.png](https://images.zenhubusercontent.com/63e10f6258011a5593f8116e/6ebebb11-20b5-437a-b124-d6f615461a21)

**Comment by zhangjing28** [comment]
Need help with this bug.

**Comment by yeyeyeyehan** [comment]
this interaction is good for now, we don't need to change the implementation ;)
