### ISSUE TITLE
Themes loading lagcy in "select themes" page

### ISSUE THREAD

**Issue by yingjingyang** [Manta-Network/manta-front-end#516]
![截屏2023-02-19 下午2.46.13.png](https://images.zenhubusercontent.com/63e10f6258011a5593f8116e/dea7a3d8-5afc-48c2-bf1a-58b046090582)

![image.png](https://images.zenhubusercontent.com/63e10f6258011a5593f8116e/69058106-be3d-4620-91ea-84d98d93ca79)

[video link](https://drive.google.com/file/d/1P5_bqrn0hB10g5-gJHJHXa5EehJtc_JC/view?usp=sharing)

**Comment by zhangjing28** [comment]
Same as #495
