### ISSUE TITLE
Select two SBT pictures, but only show one SBT picture in "Mint Your zkSBT" page

### ISSUE THREAD

**Issue by yingjingyang** [Manta-Network/manta-front-end#521]
"Mint Your zkSBT" page

![截屏2023-02-20 下午3.31.06.png](https://images.zenhubusercontent.com/63e10f6258011a5593f8116e/f3f12a22-fe1c-420a-ac39-3d66323b5520)

checkout window

![截屏2023-02-20 下午3.30.56.png](https://images.zenhubusercontent.com/63e10f6258011a5593f8116e/ffded9c7-6987-4609-9b0b-01fc6d77faf1)

**Comment by pandaxuan** [comment]
Acceptable, fix this bug in the next version
