### ISSUE TITLE
"Confirm" button is not clickable when I have enough balance

### ISSUE THREAD

**Issue by yingjingyang** [Manta-Network/manta-front-end#525]
![截屏2023-02-20 下午4.05.45.png](https://images.zenhubusercontent.com/63e10f6258011a5593f8116e/74d17248-61f1-43b6-83db-3714fc9898e1)

![image.png](https://images.zenhubusercontent.com/63e10f6258011a5593f8116e/49a5845b-1afe-4aae-8083-c181087372bc)

**Comment by zhangjing28** [comment]
That is not because of your balance, the gas fee should be not zero before you can click the button
