### ISSUE TITLE
Watermark does not match the design

### ISSUE THREAD

**Issue by yingjingyang** [Manta-Network/manta-front-end#533]
design draft
![截屏2023-02-20 下午4.21.16.png](https://images.zenhubusercontent.com/63e10f6258011a5593f8116e/00eb949e-3d03-450e-814c-7ed56454966f)

current website:
![截屏2023-02-20 下午4.19.36.png](https://images.zenhubusercontent.com/63e10f6258011a5593f8116e/fdfac8c4-8e8d-4fa4-b390-6cfc51659518)

**Comment by zhangjing28** [comment]
This is the final version of the watermark design: https://www.figma.com/file/KuEwMlZu9AcvVrMkLQoA1n/SBT-Coin-Avatar---Ideas?node-id=426%3A5248
