### ISSUE TITLE
Should provide hint message in "Mint Your zkSBT" 

### ISSUE THREAD

**Issue by yingjingyang** [Manta-Network/manta-front-end#548]
design draft:

![截屏2023-02-21 下午2.34.46.png](https://images.zenhubusercontent.com/63e10f6258011a5593f8116e/8ae0e866-f06d-4db0-8565-1e4e9cff937d)

current website;
![截屏2023-02-21 下午2.29.56.png](https://images.zenhubusercontent.com/63e10f6258011a5593f8116e/0b0a8efb-ae99-4741-8355-5e36afc998cf)

**Comment by pandaxuan** [comment]
马上
