### ISSUE TITLE
button "Click to copy all zkSBT IDs" not changed after clicking

### ISSUE THREAD

**Issue by yingjingyang** [Manta-Network/manta-front-end#577]
![截屏2023-02-22 下午12.04.38.png](https://images.zenhubusercontent.com/63e10f6258011a5593f8116e/7f8575ab-776f-413d-8bcc-df373df88701)

**Comment by yeyeyeyehan** [comment]
Is it possible to add another status after clicking this button, the button changes to 50% opacity with text on top saying 'copied' ?

**Comment by zhangjing28** [comment]
> Is it possible to add another status after clicking this button, the button changes to 50% opacity with text on top saying 'copied' ?

Yeah， I think it's possible. Pls attach the design here and I will finish the codes

**Comment by yeyeyeyehan** [comment]
https://www.figma.com/file/t7AdCuflV4kJhb9H3O3Zjz/NPO-SBT?node-id=0%3A1&t=e1bP4ZJXsx5XqgrY-1
I marked it out with a red stroke you can see the button status change. Let me know if there are anything else you need! thank you!!

**Comment by zhangjing28** [comment]
That' all I need, thanks for your help😊
