### ISSUE TITLE
The border style is wrong

### ISSUE THREAD

**Issue by yingjingyang** [Manta-Network/manta-front-end#592]
design draft

![截屏2023-02-22 下午3.49.39.png](https://images.zenhubusercontent.com/63e10f6258011a5593f8116e/31353464-808e-4882-82a7-e89e5addcd2a)

current website:

![截屏2023-02-22 下午3.49.53.png](https://images.zenhubusercontent.com/63e10f6258011a5593f8116e/6731e386-385e-4746-bf39-882ee8ee9f41)

**Comment by zhangjing28** [comment]
The style here should be the same as the style in other places, so there is no border here. 
![image](https://user-images.githubusercontent.com/38777378/220632359-a8107ad0-a003-489e-ae52-c1ba38da5ca7.png)

**Comment by yingjingyang** [comment]
Need to be checked in v1.1
