### ISSUE TITLE
The icon of notification lost when network is broken

### ISSUE THREAD

**Issue by yingjingyang** [Manta-Network/manta-front-end#602]
Reproduce steps:
1. Do a "Public" to "Private" transaction in "zkTransact" page
2. Sign the transaction
3. When waiting for the transaction response, disconnect the network

Or:
just do a "Public" to "Public" transaction in "zkTransact"

[Video link](https://drive.google.com/file/d/1RO3q4-F6DliPTwotFXYAycmsdiFi9AdG/view?usp=sharing)

 ![截屏2023-02-23 上午11.00.03.png](https://images.zenhubusercontent.com/63e10f6258011a5593f8116e/860df7e9-03ed-4479-8b6f-fbef903c30fc)

**Comment by Kevingislason** [comment]
The icon isn't available because element-react fetches it from a remote repository. We can find a different library to replace them, but this is a decently big refactor.
