### ISSUE TITLE
Test Front-End Deployment URL

### ISSUE THREAD

**Issue by stechu** [Manta-Network/manta-front-end#66]
When a new front-end is online, we would like to deploy it to a test url for sanity checking first.

**Comment by Kevingislason** [comment]
todo: research Vercel

**Comment by dansofter** [comment]
1. We need to connect our github account to Vercel.
2. We can link each branch to different domains like master -> app.dolphin.manta.network, staging -> staging.dolphin.manta.network, etc.
3. Vercel subscribes to the git repo changes and whenever a commit or PR is made, it deploys the commit or PR to a randomized domain like manta-123.vercel.app so we can test things out there. (All domains are SSL certified.)

@stechu @Kevingislason

**Comment by Kevingislason** [comment]
Closing, Danny got Vercel working
