### ISSUE TITLE
Current balance is wrong in private

### ISSUE THREAD

**Issue by Tbaut** [Manta-Network/manta-front-end#69]
Hey, I just tried the UI on Dolphin with the Linux signer and found the following issue:
If you transfer "to private" say 2 KSM. Then what the account will have 2pKSM. Now if I switch to another account that should have no pKSM, it still shows 2pKSM. This account has never interacted with Dolphin before.

The display of public tokens is fine.

**Comment by stechu** [comment]
Hi @Tbaut,
This is expected since the pKSM is not attached to your Polkadot account. This is purely associated with the secret that signer kept. We will make this more clear in the UI as well as in the documentation next version.

**Comment by Tbaut** [comment]
aaah now things clicked. The Signer actually hosts and account, hence the mnemonic, and when we send some tokens to private, we actually send some token to the Signer.

Thanks for the explanation, I'll think about it and eventually come up with suggestions.

Out of my head: The fact that the UI for public and private looks exactly the same, with the same fields, made me think that the private area is also connected to the selected account. I bet it'd be good to have a tab rather than a switch, and not show the selected account there. The switch made me thing the same account can "go to" private, which is not true.

Also the copy "to private" could be something like "send to the private account". I think it may help.

**Comment by stechu** [comment]
> aaah now things clicked. The Signer actually hosts and account, hence the mnemonic, and when we send some tokens to private, we actually send some token to the Signer.
> 
> Thanks for the explanation, I'll think about it and eventually come up with suggestions.
> 
> Out of my head: The fact that the UI for public and private looks exactly the same, with the same fields, made me think that the private area is also connected to the selected account. I bet it'd be good to have a tab rather than a switch, and not show the selected account there. The switch made me thing the same account can "go to" private, which is not true.
> 
> Also the copy "to private" could be something like "send to the private account". I think it may help.

Thanks for the suggestion. This is definitely a good direction to make a more intuitive UI.

We are going to do a private-payment protocol upgrade in testnet V2 pretty soon, the major difference is that the shielded address will be reusable (currently it is one time use only).  With that, the overall UI logic will be changed significantly as well.
