### ISSUE TITLE
It's better to block the scroll area in "Upload page" when is processing

### ISSUE THREAD

**Issue by yingjingyang** [Manta-Network/manta-front-end#806]
[Video Link](https://drive.google.com/file/d/12oTDSgI7GIX3_PNwxAPdq9wX4X3XEQ7x/view?usp=sharing)

![截屏2023-03-20 下午11.48.58.png](https://images.zenhubusercontent.com/63e10f6258011a5593f8116e/51b02863-389a-4cf4-ab86-6e8d2d285ae1)

**Comment by zhangjing28** [comment]
I don't think so, scroll has nothing related to the processing

**Comment by pandaxuan** [comment]
可以接受 先不改了
