### ISSUE TITLE
In Minted page, when switch to account has no NFT, need to go back to homepage

### ISSUE THREAD

**Issue by yingjingyang** [Manta-Network/manta-front-end#812]
[Video Link](https://drive.google.com/file/d/1TO88wYtNmbG7aqfNWygs1e4KOWUuFThT/view?usp=sharing)

![截屏2023-03-21 下午2.49.45.png](https://images.zenhubusercontent.com/63e10f6258011a5593f8116e/329ed357-3f74-4d9e-8019-23e87b32cef5)

**Comment by pandaxuan** [comment]
需要回到homepage
