### ISSUE TITLE
When jump into Analyzing page from home page, the notification position is strange

### ISSUE THREAD

**Issue by yingjingyang** [Manta-Network/manta-front-end#815]
[Video Link](https://drive.google.com/file/d/1BfKxrewgL7pR3Yc61ZQ4A4rGxr7ams3d/view?usp=sharing)

![截屏2023-03-21 下午3.27.12.png](https://images.zenhubusercontent.com/63e10f6258011a5593f8116e/a13477ce-03db-4fe1-9a6c-ec5b2140d975)

**Comment by zhangjing28** [comment]
That's acceptable to me.

**Comment by pandaxuan** [comment]
需要改一下
