### ISSUE TITLE
Links that leave the domain (go to new tab) should indicate with an arrow

### ISSUE THREAD

**Issue by bhgomes** [Manta-Network/manta-front-end#84]
We should indicate with an NE-pointing arrow or arrow in box

![image](https://user-images.githubusercontent.com/9126085/166113647-1c0cf6de-beac-406b-b31c-dab604380f7d.png)

especially for these links, Govern, and Docs, which don't look like they would leave the page:

<img width="265" alt="Screen Shot 2022-04-30 at 12 14 58" src="https://user-images.githubusercontent.com/9126085/166113659-76a2d3f4-0d84-4d4a-8c85-2301ede1a064.png">

Uniswap does this with just an arrow and no box (note the four locations on screen):

<img width="1116" alt="Screen Shot 2022-04-30 at 12 19 12" src="https://user-images.githubusercontent.com/9126085/166113703-c0eda763-0afe-456d-8ba6-d8f7d7a1015c.png">

**Comment by dansofter** [comment]
@bhgomes looks like this has been resolved.

**Comment by bhgomes** [comment]
Resolved during Testnet v2 hacking session.
