### ISSUE TITLE
Inconsistent vertical distribution of elements 

### ISSUE THREAD

**Issue by bhgomes** [Manta-Network/manta-front-end#86]
The top section has a bottom margin with invisible text "Sufficient Balance" which leaves the vertical spacing inconsistent:

<img width="593" alt="Screen Shot 2022-04-30 at 12 55 50" src="https://user-images.githubusercontent.com/9126085/166115104-4df76d2a-53fc-4e41-b38d-28901136f924.png">
<img width="614" alt="Screen Shot 2022-04-30 at 12 56 01" src="https://user-images.githubusercontent.com/9126085/166115105-5d00270e-6c34-4096-996e-4589c26ed66e.png">
<img width="583" alt="Screen Shot 2022-04-30 at 12 58 13" src="https://user-images.githubusercontent.com/9126085/166115106-bb16c533-d9c5-49cf-bc61-32b0eaa62828.png">

The arrow should ideally be centered between the two elements. This discrepancy is true for all four public/private modes.

**Comment by Kevingislason** [comment]
closed in #318
