### ISSUE TITLE
Transfer UI not centered

### ISSUE THREAD

**Issue by bhgomes** [Manta-Network/manta-front-end#87]
Because of the space that the left margin takes up, the actual UI that the user interacts with is not centered horizontally across the entire screen:

<img width="1680" alt="Screen Shot 2022-04-30 at 13 02 13" src="https://user-images.githubusercontent.com/9126085/166115218-5c350045-8c6a-4b8d-a694-5e9e3542b695.png">

**Comment by dansofter** [comment]
@bhgomes Do you mean that the form should be centered horizontally in the viewport regardless the left nav bar?

**Comment by bhgomes** [comment]
Not sure what the right choice is here, but on certain device widths, it looks awkward that the transfer component is not centered horizontally.
