### ISSUE TITLE
【MantaPay v4】popup style for wallet connect for MantaPay v3 is very strange

### ISSUE THREAD

**Issue by yingjingyang** [Manta-Network/manta-front-end#923]
![截屏2023-04-19 下午4.45.33.png](https://images.zenhubusercontent.com/63e10f6258011a5593f8116e/112e38d6-cf12-4c1b-95fe-8b23e797903b)

**Comment by Kevingislason** [comment]
This is part of the original design for MantaPay:
https://www.figma.com/file/9nAYHsYlfHmyT8RL5P8ISZ/Manta-Pay?node-id=221-1804&t=YJTGeEIbrMSkydYm-0
