### ISSUE TITLE
【MantaPay v4】text should be changed

### ISSUE THREAD

**Issue by yingjingyang** [Manta-Network/manta-front-end#924]
maybe it's better to use MantaPay

![截屏2023-04-19 下午4.47.27.png](https://images.zenhubusercontent.com/63e10f6258011a5593f8116e/c8e215a5-2e79-40c3-a551-3b596a208922)

**Comment by Kevingislason** [comment]
This text is part of the original design for MantaPay
https://www.figma.com/file/9nAYHsYlfHmyT8RL5P8ISZ/Manta-Pay?node-id=221-1804&t=YJTGeEIbrMSkydYm-0
