### ISSUE TITLE
[MantaPay v4】polkadot.js account not raised to top of accounts list

### ISSUE THREAD

**Issue by Kevingislason** [Manta-Network/manta-front-end#950]
<img width="474" alt="Screen Shot 2023-04-20 at 11 34 49 PM" src="https://user-images.githubusercontent.com/33131270/233534909-f0ff9853-5ad3-45a6-9ca4-90cde420d46e.png">

**Comment by jasonintju** [comment]
How to reproduce this bug?

**Comment by Kevingislason** [comment]
> How to reproduce this bug?

- Get polkadot polkadot.js and all other wallets to forget the front end. 
- Clear front end local storage
- Connect to front end with polkadot.js
